# Generated by Django 5.0.2 on 2024-02-15 19:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to=blog.models.user_directory_path),
        ),
    ]
